import type { IFosterPage } from '@/models/foster-form'

const yesNoOptions = ['Yes', 'No']

export const PAGES_1_TO_5: IFosterPage[] = [
  {
    id: 1,
    title: 'Page 1: Personal & Professional Profile',
    questions: [
      { id: 'q1', number: 1, label: 'Full Name & Any Aliases', type: 'text', required: true },
      { id: 'q2', number: 2, label: 'Date of Birth (Must be 18+)', type: 'date', required: true },
      { id: 'q3', number: 3, label: 'Primary Phone Number', type: 'tel', required: true },
      { id: 'q4', number: 4, label: 'Secondary Phone Number', type: 'tel' },
      { id: 'q5', number: 5, label: 'Email Address', type: 'email', required: true },
      { id: 'q6', number: 6, label: 'Address', type: 'text', required: true },
      { id: 'q6_city', number: 6, label: 'City', type: 'text', required: true },
      { id: 'q6_zip', number: 6, label: 'Zip', type: 'text', required: true },
      { id: 'q91', number: 3, label: 'Emergency Contact Name', type: 'text', required: true },
      { id: 'q92', number: 3, label: 'Emergency Contact Phone', type: 'tel', required: true },
      { id: 'q7', number: 7, label: 'Current Occupation & Employer', type: 'text', required: true },
      { id: 'q8', number: 8, label: "Who will be the main person responsible for the pet's care?", type: 'text', required: true },
      { id: 'q9', number: 9, label: 'Please describe your typical daily routine.', type: 'textarea', required: true },
      { id: 'q10', number: 10, label: 'What specifically drew you to foster for IDOHR?', type: 'textarea', required: true },
    ],
  },
  {
    id: 2,
    title: 'Page 2: Home, Yard & Neighborhood',
    questions: [
      { id: 'q11', number: 11, label: 'Housing Status', type: 'select', required: true, options: ['Own', 'Rent', 'Live with family'] },
      { id: 'q12', number: 12, label: 'Provide contact info and confirm pets are allowed.', type: 'textarea', required: true },
      { id: 'q13', number: 13, label: 'Has every adult in the home agreed to this?', type: 'select', required: true, options: yesNoOptions },
      { id: 'q14', number: 14, label: 'Please list ages of all children in the home.', type: 'textarea', required: true },
      { id: 'q15', number: 15, label: 'Have the children lived with animals before?', type: 'textarea', required: true },
      { id: 'q16', number: 16, label: 'Describe the fence (height, material, gate security).', type: 'textarea', speciesScope: 'dog' },
      { id: 'q17', number: 17, label: 'If you have no yard, how will you ensure the pet gets exercise?', type: 'textarea', required: true, speciesScope: 'dog' },
      { id: 'q18', number: 18, label: 'Neighborhood Environment', type: 'select', required: true, options: ['Busy city', 'Quiet suburb', 'Rural/Farm', 'Mixed'] },
      { id: 'q19', number: 19, label: 'Home Activity Level', type: 'select', required: true, options: ['Quiet/Sedate', 'Moderate', 'High/Active'] },
      { id: 'q20', number: 20, label: 'Have you checked for toxic plants, loose wires, and small ingestible objects?', type: 'select', required: true, options: yesNoOptions },
    ],
  },
  {
    id: 3,
    title: 'Page 3: The Foster Environment',
    questions: [
      { id: 'q21', number: 21, label: 'How many hours per day will the pet be alone?', type: 'number', required: true },
      { id: 'q22', number: 22, label: 'Where will the pet stay when you are out of the house?', type: 'text', required: true },
      { id: 'q23', number: 23, label: 'Where will the pet sleep?', type: 'text', required: true },
      { id: 'q24', number: 24, label: 'Which room will be used for initial decompression?', type: 'text', required: true },
      { id: 'q25', number: 25, label: 'Where will the designated bathroom area be?', type: 'text', required: true, speciesScope: 'cat' },
      { id: 'q26', number: 26, label: 'Can you keep the foster separate from your pets for 14 days?', type: 'select', required: true, options: yesNoOptions },
      { id: 'q27', number: 27, label: 'Do you have frequent visitors or strangers in the home?', type: 'textarea', required: true },
      { id: 'q28', number: 28, label: "Does your home have working AC/Heat for the pet's comfort?", type: 'select', required: true, options: yesNoOptions },
      { id: 'q29', number: 29, label: 'Does anyone in the home have allergies to fur, dander, or dust?', type: 'textarea', required: true },
      { id: 'q30', number: 30, label: 'Do you smoke or vape inside the home?', type: 'select', required: true, options: yesNoOptions },
    ],
  },
  {
    id: 4,
    title: 'Page 4: Current Resident Pets',
    questions: [
      { id: 'q30_hasCurrentPets', number: 30, label: 'Do you currently have any pets in your home?', type: 'select', required: true, options: yesNoOptions },
      { id: 'q31', number: 31, label: 'List all pets (Name, Species, Breed, Age, Sex).', type: 'textarea' },
      { id: 'q32', number: 32, label: 'How long have you owned each of your current pets?', type: 'textarea' },
      { id: 'q33', number: 33, label: 'Are all current pets fixed? (If no, why?)', type: 'textarea', required: true },
      { id: 'q34', number: 34, label: 'Are all pets current on core vaccines?', type: 'textarea', required: true },
      { id: 'q35', number: 35, label: 'What brands of flea/tick/heartworm meds do you use?', type: 'textarea' },
      { id: 'q36', number: 36, label: 'Do any current pets have FIV, FeLV, URI, or skin issues?', type: 'textarea' },
      { id: 'q37', number: 37, label: 'Do your pets guard food, toys, or people?', type: 'textarea' },
      { id: 'q38', number: 38, label: 'How does your pet act when seeing new animals through a fence?', type: 'textarea' },
      { id: 'q39', number: 39, label: 'Has your current pet lived with this species before?', type: 'textarea', required: true },
      { id: 'q40', number: 40, label: 'Name and phone number of your current clinic.', type: 'textarea', required: true },
    ],
  },
  {
    id: 5,
    title: 'Page 5: Past Pet History',
    questions: [
      { id: 'q40_hasPastPets', number: 40, label: 'Have you had pets in the past?', type: 'select', required: true, options: yesNoOptions },
      { id: 'q41', number: 41, label: 'List pets owned in the last decade not currently with you.', type: 'textarea' },
      { id: 'q42', number: 42, label: 'What happened to each of those pets? (Passed away, rehomed, etc.).', type: 'textarea' },
      { id: 'q43', number: 43, label: 'Have you ever taken an animal to a shelter?', type: 'select', required: true, options: yesNoOptions },
      { id: 'q44', number: 44, label: 'Have any pets ever escaped or gone missing under your care?', type: 'select', required: true, options: yesNoOptions },
      { id: 'q45', number: 45, label: 'Has a pet in your care ever experienced a preventable injury?', type: 'select', required: true, options: yesNoOptions },
      { id: 'q46', number: 46, label: 'Historically, have your pets been indoor or outdoor?', type: 'textarea' },
      { id: 'q47', number: 47, label: 'Have you ever attended professional obedience or socialization classes?', type: 'textarea' },
      { id: 'q48', number: 48, label: 'Have you ever cared for a pet with a chronic condition (Diabetes, etc.)?', type: 'textarea' },
      { id: 'q49', number: 49, label: 'Have you ever rehomed a pet due to a move, breakup, or new baby?', type: 'textarea' },
      { id: 'q50', number: 50, label: 'What is the longest you have ever owned a single pet?', type: 'textarea' },
    ],
  },
]
